create schema if not exists products_petrov_vv;
create table products_petrov_vv.carts (id serial not null, promocode varchar(255), primary key (id));
create table products_petrov_vv.products (count integer not null, id serial not null, price numeric(38,2) not null, name varchar(255) not null, primary key (id));
create table products_petrov_vv.products_carts (count integer not null, id serial not null, id_cart integer not null, id_product integer not null, primary key (id));
create table products_petrov_vv.roles (id serial not null, name varchar(20) check (name in ('ROLE_USER','ROLE_ADMIN')), primary key (id));
create table products_petrov_vv.user_roles (role_id integer not null, user_id bigint not null, primary key (role_id, user_id));
create table products_petrov_vv.users (cart_id integer, id bigserial not null, email varchar(255), name varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id), constraint UKr43af9ap4edm43mmtq01oddj6 unique (username), constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email));
alter table if exists products_petrov_vv.products_carts add constraint FK58gy0a22e614p332h9d1b2wsg foreign key (id_cart) references products_petrov_vv.carts;
alter table if exists products_petrov_vv.products_carts add constraint FK5xn82l6dcw7ltw5q14me13yuk foreign key (id_product) references products_petrov_vv.products;
alter table if exists products_petrov_vv.user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references products_petrov_vv.roles;
alter table if exists products_petrov_vv.user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references products_petrov_vv.users;
alter table if exists products_petrov_vv.users add constraint FKdv26y3bb4vdmsr89c9ppnx85w foreign key (cart_id) references products_petrov_vv.carts;
