###
POST http://localhost:8080/shopping-carts/11
Content-Type: application/json

{
  "id": 5
}

###
PUT http://localhost:8080/shopping-carts/11/product/5
Content-Type: application/json

{
  "count": 4
}

###
DELETE http://localhost:8080/shopping-carts/7/products/3