###
POST http://localhost:8080/shopping-carts/2
Content-Type: application/json

{
  "id": 2
}

###
PUT http://localhost:8080/shopping-carts/6/product/14
Content-Type: application/json

{
  "count": 4
}

###
DELETE http://localhost:8080/shopping-carts/2/products/2

###
GET http://localhost:8080/shopping-carts/1