###
POST http://localhost:8080/clients
Content-Type: application/json

{
  "name": "Misha",
  "login": "misha",
  "password": "3t45qfg",
  "email": "f423q3@wf.w"
}

###
GET http://localhost:8080/clients/773910

###
DELETE http://localhost:8080/clients/773910

###
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Морковь",
  "price": 70
}

###
PUT http://localhost:8080/products
Content-Type: application/json

{
  "id": 950979,
  "name": "Яблоко",
  "price": 70
}

###
DELETE http://localhost:8080/products/217298

###
GET http://localhost:8080/products/950979

###
GET http://localhost:8080/products
Content-Type: application/json

###
POST http://localhost:8080/shopping-carts/1
Content-Type: application/json

{
  "id": 2
}

###
PUT http://localhost:8080/shopping-carts/1/product/25
Content-Type: application/json

{
  "quantity": 4
}

###
DELETE http://localhost:8080/shopping-carts/123/products/123

###
POST http://localhost:8080/payment
Content-Type: application/json

{
  "userId": 1,
  "sum": 12
}